# Secrets module — runtime app credentials in AWS Secrets Manager.
#
# Provisions:
#   - Auto-generated 32-byte hex secrets for the master KEK + auth +
#     jwt + AV-webhook signing key. Generated by `random_id` (Go's
#     crypto/rand under the hood; cryptographically secure).
#   - Empty containers for OAuth client secrets (Google, Microsoft).
#     The secret_version is written with a placeholder; operator
#     replaces via `aws secretsmanager put-secret-value` after first
#     apply. `lifecycle.ignore_changes = [secret_string]` keeps
#     terraform from drift-reverting the operator's value.
#   - One aggregated `runtime-secrets-read` IAM policy granting
#     GetSecretValue + DescribeSecret on EVERY runtime secret —
#     including the RDS-managed master credentials and Redis AUTH
#     token from the database/redis modules (passed via
#     additional_secret_arns).
#
# Out of scope here: the app workload role itself. The storage module
# already optionally creates one; an upcoming compute epic will land
# the canonical role and attach this policy + the storage policy
# together. For now the IAM policy ARN is exposed as a stable
# contract for any role that wants to consume it.
#
# CRITICAL — DATA_ENCRYPTION_KEY:
#   Losing this value invalidates every encrypted column written under
#   it (Epic B field-level encryption). Recovery window is 30 days
#   (AWS maximum) so an accidental terraform destroy is recoverable
#   if caught quickly. The Epic B operator runbook documents the
#   v1→v2 sweep used for planned rotation; this module's job is just
#   to host the value, not to rotate it.

# ── Generated secrets (32-byte hex; matches the format documented
#    in deploy/.env.prod.example: "32_BYTES_HEX") ─────────────────────
resource "random_id" "data_encryption_key" {
  byte_length = 32
}

resource "random_id" "auth_secret" {
  byte_length = 32
}

resource "random_id" "jwt_secret" {
  byte_length = 32
}

resource "random_id" "av_webhook_secret" {
  byte_length = 32
}

# ── Secret containers ────────────────────────────────────────────────
resource "aws_secretsmanager_secret" "data_encryption_key" {
  name                    = "${var.name_prefix}-data-encryption-key"
  description             = "Master KEK for app field-level encryption (Epic B). LOSS = LOSS OF ALL ENCRYPTED DATA. ${var.data_encryption_key_recovery_days}-day recovery window."
  recovery_window_in_days = var.data_encryption_key_recovery_days
  kms_key_id              = var.kms_key_arn

  tags = merge(var.tags, {
    Sensitivity = "critical"
    Purpose     = "field-encryption-master-key"
  })
}

resource "aws_secretsmanager_secret_version" "data_encryption_key" {
  secret_id     = aws_secretsmanager_secret.data_encryption_key.id
  secret_string = random_id.data_encryption_key.hex
}

resource "aws_secretsmanager_secret" "auth_secret" {
  name                    = "${var.name_prefix}-auth-secret"
  description             = "NextAuth session-signing key. Rotation invalidates active sessions; rotate during low-traffic windows."
  recovery_window_in_days = var.secret_recovery_days
  kms_key_id              = var.kms_key_arn

  tags = merge(var.tags, {
    Sensitivity = "high"
    Purpose     = "session-signing"
  })
}

resource "aws_secretsmanager_secret_version" "auth_secret" {
  secret_id     = aws_secretsmanager_secret.auth_secret.id
  secret_string = random_id.auth_secret.hex
}

resource "aws_secretsmanager_secret" "jwt_secret" {
  name                    = "${var.name_prefix}-jwt-secret"
  description             = "JWT signing key for API tokens."
  recovery_window_in_days = var.secret_recovery_days
  kms_key_id              = var.kms_key_arn

  tags = merge(var.tags, {
    Sensitivity = "high"
    Purpose     = "api-jwt-signing"
  })
}

resource "aws_secretsmanager_secret_version" "jwt_secret" {
  secret_id     = aws_secretsmanager_secret.jwt_secret.id
  secret_string = random_id.jwt_secret.hex
}

resource "aws_secretsmanager_secret" "av_webhook_secret" {
  name                    = "${var.name_prefix}-av-webhook-secret"
  description             = "HMAC key for the antivirus scan-result webhook (POST /api/storage/av-webhook)."
  recovery_window_in_days = var.secret_recovery_days
  kms_key_id              = var.kms_key_arn

  tags = merge(var.tags, {
    Sensitivity = "high"
    Purpose     = "av-webhook-hmac"
  })
}

resource "aws_secretsmanager_secret_version" "av_webhook_secret" {
  secret_id     = aws_secretsmanager_secret.av_webhook_secret.id
  secret_string = random_id.av_webhook_secret.hex
}

# ── Operator-supplied secrets (OAuth) ────────────────────────────────
# Terraform creates the container with a placeholder. Operator runs
# `aws secretsmanager put-secret-value --secret-id <name> --secret-string <real>`
# after first apply. ignore_changes prevents drift-revert.
resource "aws_secretsmanager_secret" "google_client_secret" {
  name                    = "${var.name_prefix}-google-client-secret"
  description             = "Google OAuth 2.0 client secret. Operator sets via `aws secretsmanager put-secret-value` after first terraform apply."
  recovery_window_in_days = var.secret_recovery_days
  kms_key_id              = var.kms_key_arn

  tags = merge(var.tags, {
    Sensitivity = "high"
    Purpose     = "oauth-google"
  })
}

resource "aws_secretsmanager_secret_version" "google_client_secret" {
  secret_id     = aws_secretsmanager_secret.google_client_secret.id
  secret_string = "PLACEHOLDER_set_via_aws_secretsmanager_put-secret-value"

  lifecycle {
    ignore_changes = [secret_string]
  }
}

resource "aws_secretsmanager_secret" "microsoft_client_secret" {
  name                    = "${var.name_prefix}-microsoft-client-secret"
  description             = "Microsoft Entra ID (Azure AD) OAuth client secret. Operator sets via `aws secretsmanager put-secret-value` after first terraform apply."
  recovery_window_in_days = var.secret_recovery_days
  kms_key_id              = var.kms_key_arn

  tags = merge(var.tags, {
    Sensitivity = "high"
    Purpose     = "oauth-microsoft"
  })
}

resource "aws_secretsmanager_secret_version" "microsoft_client_secret" {
  secret_id     = aws_secretsmanager_secret.microsoft_client_secret.id
  secret_string = "PLACEHOLDER_set_via_aws_secretsmanager_put-secret-value"

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# ── IAM policy: read all runtime secrets ─────────────────────────────
# Resources are listed by ARN (NOT `*`) so the workload role's
# blast radius is exactly the set of secrets enumerated here plus
# the additional ARNs passed in.
locals {
  module_secret_arns = [
    aws_secretsmanager_secret.data_encryption_key.arn,
    aws_secretsmanager_secret.auth_secret.arn,
    aws_secretsmanager_secret.jwt_secret.arn,
    aws_secretsmanager_secret.av_webhook_secret.arn,
    aws_secretsmanager_secret.google_client_secret.arn,
    aws_secretsmanager_secret.microsoft_client_secret.arn,
  ]

  all_secret_arns = concat(local.module_secret_arns, var.additional_secret_arns)
}

data "aws_iam_policy_document" "runtime_secrets_read" {
  statement {
    sid    = "ReadRuntimeSecrets"
    effect = "Allow"

    actions = [
      "secretsmanager:GetSecretValue",
      "secretsmanager:DescribeSecret",
    ]

    resources = local.all_secret_arns
  }
}

resource "aws_iam_policy" "runtime_secrets_read" {
  name        = "${var.name_prefix}-runtime-secrets-read"
  description = "Read access to all runtime secrets for the ${var.name_prefix} app workload."
  policy      = data.aws_iam_policy_document.runtime_secrets_read.json

  tags = var.tags
}
