/**
 * GET /api/docs — Swagger UI for the OpenAPI 3.1 spec.
 *
 * GAP-10 step 4. Renders the interactive API documentation in
 * non-production environments, fetching the spec from `/openapi.json`
 * (served statically from `public/openapi.json`, generated by
 * `npm run openapi:generate`).
 *
 * Production exposure model: HARD 404 in production. Two layers of
 * defense — (1) the route handler short-circuits before producing any
 * HTML; (2) the route is in the read-rate-limit exclusion list
 * (`apiReadRateLimit.ts`) which is sized for monitoring traffic, not
 * doc-portal traffic, so even a config drift that re-enables the
 * route in production would limit blast radius.
 *
 * Why CDN for Swagger UI:
 *   - No new npm dependency, no bundle weight on every Next.js build,
 *     no risk of pulling Swagger's transitive deps into the prod
 *     bundle.
 *   - Dev-only consumption — the CDN reach is acceptable.
 *   - Pinned version (^5.x) so the UI shape is reproducible.
 *
 * If a future requirement forces self-hosting (CSP frame-src concerns,
 * air-gapped staging, etc.), swap to the `swagger-ui-dist` package
 * and serve its assets from `public/swagger-ui/`.
 */
import { NextResponse } from 'next/server';
import { withApiErrorHandling } from '@/lib/errors/api';

const SWAGGER_UI_VERSION = '5.17.14';
const SWAGGER_CSS = `https://cdn.jsdelivr.net/npm/swagger-ui-dist@${SWAGGER_UI_VERSION}/swagger-ui.css`;
const SWAGGER_JS = `https://cdn.jsdelivr.net/npm/swagger-ui-dist@${SWAGGER_UI_VERSION}/swagger-ui-bundle.js`;
const SWAGGER_PRESET_JS = `https://cdn.jsdelivr.net/npm/swagger-ui-dist@${SWAGGER_UI_VERSION}/swagger-ui-standalone-preset.js`;

/**
 * True when the docs route is allowed to render HTML.
 *
 *   - Production: false. Always 404.
 *   - Test: false. The route only exists for interactive use.
 *   - Development + staging: true.
 *
 * Operators who genuinely need the docs in a production-like
 * environment (e.g. for partner SDK debugging) should hit the
 * staging deploy where it's enabled.
 */
function isDocsEnabled(): boolean {
    const nodeEnv = process.env.NODE_ENV;
    if (nodeEnv === 'production') return false;
    if (nodeEnv === 'test') return false;
    return true;
}

// Epic E — wrapped for x-request-id + standardized error contract.
// Never throws in normal operation; an unexpected runtime error in
// the HTML build path is now reported as a clean 5xx ApiErrorResponse
// instead of a Next.js stack-trace page.
export const GET = withApiErrorHandling(async (): Promise<NextResponse> => {
    if (!isDocsEnabled()) {
        // Match Next.js's default 404 shape so this route is
        // indistinguishable from a route that never existed.
        return new NextResponse('Not Found', {
            status: 404,
            headers: { 'Content-Type': 'text/plain; charset=utf-8' },
        });
    }

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="noindex, nofollow" />
  <title>Inflect Compliance API — interactive docs</title>
  <link rel="stylesheet" href="${SWAGGER_CSS}" />
  <style>
    body { margin: 0; }
    .topbar { display: none; }
    /* Distinguish dev/staging visually so a screenshot is unambiguous. */
    body::before {
      content: "DEVELOPMENT — interactive API docs";
      display: block;
      background: #fbbf24;
      color: #1f2937;
      padding: 6px 16px;
      font: 600 12px/1.4 ui-sans-serif, system-ui, sans-serif;
      letter-spacing: 0.06em;
      text-transform: uppercase;
    }
  </style>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="${SWAGGER_JS}" crossorigin="anonymous"></script>
  <script src="${SWAGGER_PRESET_JS}" crossorigin="anonymous"></script>
  <script>
    window.addEventListener('load', function () {
      window.ui = SwaggerUIBundle({
        url: '/openapi.json',
        dom_id: '#swagger-ui',
        deepLinking: true,
        layout: 'BaseLayout',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset,
        ],
      });
    });
  </script>
</body>
</html>
`;

    return new NextResponse(html, {
        status: 200,
        headers: {
            'Content-Type': 'text/html; charset=utf-8',
            // Belt-and-braces: even though isDocsEnabled() blocks
            // production rendering, the response itself signals to
            // any cache that this is a dev-only document.
            'Cache-Control': 'no-store',
            'X-Robots-Tag': 'noindex, nofollow',
        },
    });
});
